### PR TITLE
client removed and server restructured to be friendly to plugins

### PR DESCRIPTION
**Pull request by SArpnt**
i hate ruby it's complete garbage they shove in english words in grammatically correct places but it doesn't work with code
none of the operators describe themselves well and there's an insane amount to memorize and nothing supports the latest version

### CODE REVIEW

**Review by tumble1999 — APPROVED** [review]

**Comment by SArpnt** [comment]
cool beans

**Comment by tumble1999** [comment]
> cool beans

I want to work out how to add you as a reviewer

**Comment by torralbaa** [comment]
Hello @SArpnt, I know you hate Ruby :wink:, but... Private Box is an _"Alternative client for Box Critters"_ so, why did you destroy the client? Also, you do not provide any replacements for this. The "remove Ruby" part sounds good to me, actually a while back I created a PR for that, but provided a replacement.

On the other hand, the server restructuring seems really good to me, and... Can you open a problem describing the SSL error you mention in README file? So we could help you.

**Comment by tumble1999** [comment]
@SArpnt @Alvarito050506 Could you 2 speak in discord, maybe schedule a meeting between the two of you's or something.
SArpnt#2731
Alvarito050506#8207
Alvarito050506#6661

Also, @Alvarito050506 can I kick one of the Alvaritos from the discord server as it's confusing having 2?

**Comment by torralbaa** [comment]
@tumble1999 Yes, it's good for me.

Of course, you can delete one of two I think I'm second, but please give me a moment to confirm it.

**Comment by Alvarito050506** [comment]
@tumble1999 Confirmed: I am the second one (Alvarito050506#8207).

**Comment by torralbaa** [comment]
Sorry, I am the first one (Alvarito050506#8207)

**Pull request merged**
