### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by tumble1999**

### CODE REVIEW

**Comment by SArpnt** [comment]
not fully sure what this is for? monitoring behavior on the server should be done by the server owner, and i can't think of what else this could be.

**Comment by torralbaa** [comment]
@SArpnt It is basically a "don't be evil" manifest for Open Source and Free Software projects like this. I personally think it is redundant but there is nothing wrong with it.

**Review by torralbaa — APPROVED** [review]

**Comment by tumble1999** [comment]
> @SArpnt It is basically a "don't be evil" manifest for Open Source and Free Software projects like this. I personally think it is redundant but there is nothing wrong with it.

isn't that google's slogan?

**Comment by torralbaa** [comment]
@tumble1999 Yes, I used it intentionally.

**Comment by GlugThePlug** [comment]
I'm having some issues with private box...

**Comment by torralbaa** [comment]
Hello @GlugThePlug! Please open an issue describing your problems...

**Comment by GlugThePlug** [comment]
hey, sorry i didn't see this before. I don't know how to run a js file. I have node but i do not know the command.

**Comment by torralbaa** [comment]
Don't worry. It isn't a Private Box problem, but depending on your platform, you can try:
 + `node YOUR_FILE_NAME` (GNU/Linux, OSX), or
 + `node.exe YOUR_FILE_NAME` (Windows).

For more info you can read the [Node.js guides](https://nodejs.org/en/docs/guides).

**Pull request merged**
